summon minecraft:armor_stand ~1.0 ~4.0 ~5.0 {Invisible:1b,Invulnerable:1b,NoGravity:1b,Marker:1b,CustomName:"torch"}
summon minecraft:armor_stand ~-5.5 ~1.0 ~ {Invisible:1b,Invulnerable:1b,NoGravity:1b,Marker:1b,CustomName:"torch"}
summon minecraft:armor_stand ~1.0 ~-4.0 ~-5.0 {Invisible:1b,Invulnerable:1b,NoGravity:1b,Marker:1b,CustomName:"torch"}
summon minecraft:armor_stand ~-4.0 ~1.0 ~5.0 {Invisible:1b,Invulnerable:1b,NoGravity:1b,Marker:1b,CustomName:"torch"}
summon minecraft:armor_stand ~-4.0 ~2.0 ~-4.0 {Invisible:1b,Invulnerable:1b,NoGravity:1b,Marker:1b,CustomName:"torch"}
summon minecraft:armor_stand ~4.5 ~-3.0 ~3.0 {Invisible:1b,Invulnerable:1b,NoGravity:1b,Marker:1b,CustomName:"torch"}
summon minecraft:armor_stand ~-5.5 ~3.0 ~ {Invisible:1b,Invulnerable:1b,NoGravity:1b,Marker:1b,CustomName:"torch"}
summon minecraft:armor_stand ~1.0 ~-6.0 ~ {Invisible:1b,Invulnerable:1b,NoGravity:1b,Marker:1b,CustomName:"torch"}
summon minecraft:armor_stand ~-3.0 ~-4.5 ~-2.0 {Invisible:1b,Invulnerable:1b,NoGravity:1b,Marker:1b,CustomName:"torch"}
summon minecraft:armor_stand ~ ~5.5 ~-1.0 {Invisible:1b,Invulnerable:1b,NoGravity:1b,Marker:1b,CustomName:"torch"}
summon minecraft:armor_stand ~5.5 ~-1.0 ~ {Invisible:1b,Invulnerable:1b,NoGravity:1b,Marker:1b,CustomName:"torch"}
summon minecraft:armor_stand ~3.0 ~-4.5 ~2.0 {Invisible:1b,Invulnerable:1b,NoGravity:1b,Marker:1b,CustomName:"torch"}
summon minecraft:armor_stand ~-3.0 ~5.5 ~ {Invisible:1b,Invulnerable:1b,NoGravity:1b,Marker:1b,CustomName:"torch"}
summon minecraft:armor_stand ~5.5 ~ ~3.0 {Invisible:1b,Invulnerable:1b,NoGravity:1b,Marker:1b,CustomName:"torch"}
summon minecraft:armor_stand ~ ~-3.0 ~5.5 {Invisible:1b,Invulnerable:1b,NoGravity:1b,Marker:1b,CustomName:"torch"}
summon minecraft:armor_stand ~ ~5.5 ~3.0 {Invisible:1b,Invulnerable:1b,NoGravity:1b,Marker:1b,CustomName:"torch"}
summon minecraft:armor_stand ~2.0 ~-3.0 ~-5.0 {Invisible:1b,Invulnerable:1b,NoGravity:1b,Marker:1b,CustomName:"torch"}
summon minecraft:armor_stand ~2.0 ~-1.0 ~6.0 {Invisible:1b,Invulnerable:1b,NoGravity:1b,Marker:1b,CustomName:"torch"}
summon minecraft:armor_stand ~5.0 ~-1.0 ~4.0 {Invisible:1b,Invulnerable:1b,NoGravity:1b,Marker:1b,CustomName:"torch"}
summon minecraft:armor_stand ~6.0 ~ ~-1.0 {Invisible:1b,Invulnerable:1b,NoGravity:1b,Marker:1b,CustomName:"torch"}
summon minecraft:armor_stand ~-5.0 ~3.0 ~-2.0 {Invisible:1b,Invulnerable:1b,NoGravity:1b,Marker:1b,CustomName:"torch"}
summon minecraft:armor_stand ~4.0 ~-4.0 ~2.0 {Invisible:1b,Invulnerable:1b,NoGravity:1b,Marker:1b,CustomName:"torch"}
summon minecraft:armor_stand ~-1.0 ~ ~-6.0 {Invisible:1b,Invulnerable:1b,NoGravity:1b,Marker:1b,CustomName:"torch"}
summon minecraft:armor_stand ~-3.0 ~-5.5 ~ {Invisible:1b,Invulnerable:1b,NoGravity:1b,Marker:1b,CustomName:"torch"}
summon minecraft:armor_stand ~-4.0 ~-4.0 ~-3.0 {Invisible:1b,Invulnerable:1b,NoGravity:1b,Marker:1b,CustomName:"torch"}
summon minecraft:armor_stand ~1.0 ~-2.0 ~-6.0 {Invisible:1b,Invulnerable:1b,NoGravity:1b,Marker:1b,CustomName:"torch"}
summon minecraft:armor_stand ~2.0 ~-6.0 ~ {Invisible:1b,Invulnerable:1b,NoGravity:1b,Marker:1b,CustomName:"torch"}
summon minecraft:armor_stand ~5.0 ~ ~4.0 {Invisible:1b,Invulnerable:1b,NoGravity:1b,Marker:1b,CustomName:"torch"}
summon minecraft:armor_stand ~6.0 ~2.0 ~1.0 {Invisible:1b,Invulnerable:1b,NoGravity:1b,Marker:1b,CustomName:"torch"}
summon minecraft:armor_stand ~-2.0 ~5.0 ~-2.0 {Invisible:1b,Invulnerable:1b,NoGravity:1b,Marker:1b,CustomName:"torch"}
summon minecraft:armor_stand ~2.0 ~-2.0 ~-5.0 {Invisible:1b,Invulnerable:1b,NoGravity:1b,Marker:1b,CustomName:"torch"}
summon minecraft:armor_stand ~5.0 ~-3.0 ~1.0 {Invisible:1b,Invulnerable:1b,NoGravity:1b,Marker:1b,CustomName:"torch"}
summon minecraft:armor_stand ~-2.0 ~ ~-6.0 {Invisible:1b,Invulnerable:1b,NoGravity:1b,Marker:1b,CustomName:"torch"}
summon minecraft:armor_stand ~-3.0 ~ ~5.5 {Invisible:1b,Invulnerable:1b,NoGravity:1b,Marker:1b,CustomName:"torch"}
summon minecraft:armor_stand ~2.0 ~1.0 ~6.0 {Invisible:1b,Invulnerable:1b,NoGravity:1b,Marker:1b,CustomName:"torch"}
summon minecraft:armor_stand ~-2.0 ~4.0 ~-4.0 {Invisible:1b,Invulnerable:1b,NoGravity:1b,Marker:1b,CustomName:"torch"}
summon minecraft:armor_stand ~-5.0 ~-3.0 ~-2.0 {Invisible:1b,Invulnerable:1b,NoGravity:1b,Marker:1b,CustomName:"torch"}
summon minecraft:armor_stand ~1.0 ~6.0 ~1.0 {Invisible:1b,Invulnerable:1b,NoGravity:1b,Marker:1b,CustomName:"torch"}
summon minecraft:armor_stand ~2.0 ~-5.0 ~3.0 {Invisible:1b,Invulnerable:1b,NoGravity:1b,Marker:1b,CustomName:"torch"}
summon minecraft:armor_stand ~-3.0 ~5.5 ~-1.0 {Invisible:1b,Invulnerable:1b,NoGravity:1b,Marker:1b,CustomName:"torch"}
summon minecraft:armor_stand ~6.0 ~-1.0 ~-1.0 {Invisible:1b,Invulnerable:1b,NoGravity:1b,Marker:1b,CustomName:"torch"}
summon minecraft:armor_stand ~2.0 ~-5.0 ~2.0 {Invisible:1b,Invulnerable:1b,NoGravity:1b,Marker:1b,CustomName:"torch"}
summon minecraft:armor_stand ~ ~5.5 ~1.0 {Invisible:1b,Invulnerable:1b,NoGravity:1b,Marker:1b,CustomName:"torch"}
summon minecraft:armor_stand ~3.0 ~-3.0 ~4.5 {Invisible:1b,Invulnerable:1b,NoGravity:1b,Marker:1b,CustomName:"torch"}
summon minecraft:armor_stand ~3.0 ~-5.5 ~-1.0 {Invisible:1b,Invulnerable:1b,NoGravity:1b,Marker:1b,CustomName:"torch"}
summon minecraft:armor_stand ~2.0 ~4.0 ~-4.0 {Invisible:1b,Invulnerable:1b,NoGravity:1b,Marker:1b,CustomName:"torch"}
summon minecraft:armor_stand ~-5.5 ~1.0 ~3.0 {Invisible:1b,Invulnerable:1b,NoGravity:1b,Marker:1b,CustomName:"torch"}
summon minecraft:armor_stand ~4.0 ~5.0 ~-1.0 {Invisible:1b,Invulnerable:1b,NoGravity:1b,Marker:1b,CustomName:"torch"}
summon minecraft:armor_stand ~-2.0 ~1.0 ~6.0 {Invisible:1b,Invulnerable:1b,NoGravity:1b,Marker:1b,CustomName:"torch"}
summon minecraft:armor_stand ~2.0 ~-5.0 ~-3.0 {Invisible:1b,Invulnerable:1b,NoGravity:1b,Marker:1b,CustomName:"torch"}
summon minecraft:armor_stand ~4.0 ~-5.0 ~ {Invisible:1b,Invulnerable:1b,NoGravity:1b,Marker:1b,CustomName:"torch"}
summon minecraft:armor_stand ~4.0 ~5.0 ~ {Invisible:1b,Invulnerable:1b,NoGravity:1b,Marker:1b,CustomName:"torch"}
summon minecraft:armor_stand ~6.5 ~ ~ {Invisible:1b,Invulnerable:1b,NoGravity:1b,Marker:1b,CustomName:"torch"}
summon minecraft:armor_stand ~3.0 ~2.0 ~4.5 {Invisible:1b,Invulnerable:1b,NoGravity:1b,Marker:1b,CustomName:"torch"}
summon minecraft:armor_stand ~-3.0 ~4.5 ~2.0 {Invisible:1b,Invulnerable:1b,NoGravity:1b,Marker:1b,CustomName:"torch"}
summon minecraft:armor_stand ~3.0 ~3.0 ~4.5 {Invisible:1b,Invulnerable:1b,NoGravity:1b,Marker:1b,CustomName:"torch"}
summon minecraft:armor_stand ~-5.0 ~2.0 ~-2.0 {Invisible:1b,Invulnerable:1b,NoGravity:1b,Marker:1b,CustomName:"torch"}
summon minecraft:armor_stand ~4.0 ~ ~-5.0 {Invisible:1b,Invulnerable:1b,NoGravity:1b,Marker:1b,CustomName:"torch"}
summon minecraft:armor_stand ~1.0 ~-6.0 ~1.0 {Invisible:1b,Invulnerable:1b,NoGravity:1b,Marker:1b,CustomName:"torch"}
summon minecraft:armor_stand ~3.0 ~4.5 ~-2.0 {Invisible:1b,Invulnerable:1b,NoGravity:1b,Marker:1b,CustomName:"torch"}
summon minecraft:armor_stand ~2.0 ~3.0 ~-5.0 {Invisible:1b,Invulnerable:1b,NoGravity:1b,Marker:1b,CustomName:"torch"}
summon minecraft:armor_stand ~-4.0 ~-1.0 ~5.0 {Invisible:1b,Invulnerable:1b,NoGravity:1b,Marker:1b,CustomName:"torch"}
summon minecraft:armor_stand ~-1.0 ~6.0 ~-1.0 {Invisible:1b,Invulnerable:1b,NoGravity:1b,Marker:1b,CustomName:"torch"}
summon minecraft:armor_stand ~-4.0 ~1.0 ~-5.0 {Invisible:1b,Invulnerable:1b,NoGravity:1b,Marker:1b,CustomName:"torch"}
summon minecraft:armor_stand ~4.0 ~-3.0 ~4.0 {Invisible:1b,Invulnerable:1b,NoGravity:1b,Marker:1b,CustomName:"torch"}
summon minecraft:armor_stand ~2.0 ~ ~6.0 {Invisible:1b,Invulnerable:1b,NoGravity:1b,Marker:1b,CustomName:"torch"}
summon minecraft:armor_stand ~-4.5 ~-4.0 ~ {Invisible:1b,Invulnerable:1b,NoGravity:1b,Marker:1b,CustomName:"torch"}
summon minecraft:armor_stand ~-5.5 ~ ~-3.0 {Invisible:1b,Invulnerable:1b,NoGravity:1b,Marker:1b,CustomName:"torch"}
summon minecraft:armor_stand ~3.0 ~-2.0 ~-4.5 {Invisible:1b,Invulnerable:1b,NoGravity:1b,Marker:1b,CustomName:"torch"}
summon minecraft:armor_stand ~-4.5 ~3.0 ~3.0 {Invisible:1b,Invulnerable:1b,NoGravity:1b,Marker:1b,CustomName:"torch"}
summon minecraft:armor_stand ~6.0 ~-1.0 ~2.0 {Invisible:1b,Invulnerable:1b,NoGravity:1b,Marker:1b,CustomName:"torch"}
summon minecraft:armor_stand ~-5.0 ~-3.0 ~-1.0 {Invisible:1b,Invulnerable:1b,NoGravity:1b,Marker:1b,CustomName:"torch"}
summon minecraft:armor_stand ~1.0 ~3.0 ~5.0 {Invisible:1b,Invulnerable:1b,NoGravity:1b,Marker:1b,CustomName:"torch"}
summon minecraft:armor_stand ~5.0 ~-4.0 ~1.0 {Invisible:1b,Invulnerable:1b,NoGravity:1b,Marker:1b,CustomName:"torch"}
summon minecraft:armor_stand ~-5.0 ~4.0 ~1.0 {Invisible:1b,Invulnerable:1b,NoGravity:1b,Marker:1b,CustomName:"torch"}
summon minecraft:armor_stand ~-2.0 ~6.0 ~ {Invisible:1b,Invulnerable:1b,NoGravity:1b,Marker:1b,CustomName:"torch"}
summon minecraft:armor_stand ~-5.0 ~1.0 ~4.0 {Invisible:1b,Invulnerable:1b,NoGravity:1b,Marker:1b,CustomName:"torch"}
summon minecraft:armor_stand ~-1.0 ~-5.0 ~4.0 {Invisible:1b,Invulnerable:1b,NoGravity:1b,Marker:1b,CustomName:"torch"}
summon minecraft:armor_stand ~-5.0 ~1.0 ~-4.0 {Invisible:1b,Invulnerable:1b,NoGravity:1b,Marker:1b,CustomName:"torch"}
summon minecraft:armor_stand ~ ~4.5 ~-4.0 {Invisible:1b,Invulnerable:1b,NoGravity:1b,Marker:1b,CustomName:"torch"}
summon minecraft:armor_stand ~-6.0 ~-1.0 ~1.0 {Invisible:1b,Invulnerable:1b,NoGravity:1b,Marker:1b,CustomName:"torch"}
summon minecraft:armor_stand ~-1.0 ~4.0 ~-5.0 {Invisible:1b,Invulnerable:1b,NoGravity:1b,Marker:1b,CustomName:"torch"}
summon minecraft:armor_stand ~ ~5.5 ~2.0 {Invisible:1b,Invulnerable:1b,NoGravity:1b,Marker:1b,CustomName:"torch"}
summon minecraft:armor_stand ~4.0 ~4.0 ~2.0 {Invisible:1b,Invulnerable:1b,NoGravity:1b,Marker:1b,CustomName:"torch"}
summon minecraft:armor_stand ~-4.0 ~5.0 ~ {Invisible:1b,Invulnerable:1b,NoGravity:1b,Marker:1b,CustomName:"torch"}
summon minecraft:armor_stand ~ ~-4.5 ~4.0 {Invisible:1b,Invulnerable:1b,NoGravity:1b,Marker:1b,CustomName:"torch"}
summon minecraft:armor_stand ~-1.0 ~-4.0 ~5.0 {Invisible:1b,Invulnerable:1b,NoGravity:1b,Marker:1b,CustomName:"torch"}
summon minecraft:armor_stand ~2.0 ~6.0 ~1.0 {Invisible:1b,Invulnerable:1b,NoGravity:1b,Marker:1b,CustomName:"torch"}
summon minecraft:armor_stand ~4.0 ~-5.0 ~-1.0 {Invisible:1b,Invulnerable:1b,NoGravity:1b,Marker:1b,CustomName:"torch"}
summon minecraft:armor_stand ~-4.0 ~-4.0 ~-2.0 {Invisible:1b,Invulnerable:1b,NoGravity:1b,Marker:1b,CustomName:"torch"}
summon minecraft:armor_stand ~-5.0 ~3.0 ~1.0 {Invisible:1b,Invulnerable:1b,NoGravity:1b,Marker:1b,CustomName:"torch"}
summon minecraft:armor_stand ~-5.0 ~-3.0 ~2.0 {Invisible:1b,Invulnerable:1b,NoGravity:1b,Marker:1b,CustomName:"torch"}
summon minecraft:armor_stand ~-6.0 ~-2.0 ~-1.0 {Invisible:1b,Invulnerable:1b,NoGravity:1b,Marker:1b,CustomName:"torch"}
summon minecraft:armor_stand ~-2.0 ~6.0 ~-1.0 {Invisible:1b,Invulnerable:1b,NoGravity:1b,Marker:1b,CustomName:"torch"}
summon minecraft:armor_stand ~-1.0 ~-5.0 ~-4.0 {Invisible:1b,Invulnerable:1b,NoGravity:1b,Marker:1b,CustomName:"torch"}
summon minecraft:armor_stand ~-1.0 ~3.0 ~5.0 {Invisible:1b,Invulnerable:1b,NoGravity:1b,Marker:1b,CustomName:"torch"}
summon minecraft:armor_stand ~-3.0 ~-1.0 ~-5.5 {Invisible:1b,Invulnerable:1b,NoGravity:1b,Marker:1b,CustomName:"torch"}
summon minecraft:armor_stand ~1.0 ~5.0 ~-3.0 {Invisible:1b,Invulnerable:1b,NoGravity:1b,Marker:1b,CustomName:"torch"}
summon minecraft:armor_stand ~-5.5 ~-1.0 ~-3.0 {Invisible:1b,Invulnerable:1b,NoGravity:1b,Marker:1b,CustomName:"torch"}
summon minecraft:armor_stand ~ ~5.5 ~-3.0 {Invisible:1b,Invulnerable:1b,NoGravity:1b,Marker:1b,CustomName:"torch"}
summon minecraft:armor_stand ~1.0 ~-6.0 ~2.0 {Invisible:1b,Invulnerable:1b,NoGravity:1b,Marker:1b,CustomName:"torch"}
summon minecraft:armor_stand ~ ~5.5 ~-2.0 {Invisible:1b,Invulnerable:1b,NoGravity:1b,Marker:1b,CustomName:"torch"}
summon minecraft:armor_stand ~ ~6.5 ~ {Invisible:1b,Invulnerable:1b,NoGravity:1b,Marker:1b,CustomName:"torch"}
summon minecraft:armor_stand ~-5.0 ~ ~4.0 {Invisible:1b,Invulnerable:1b,NoGravity:1b,Marker:1b,CustomName:"torch"}
summon minecraft:armor_stand ~5.5 ~1.0 ~ {Invisible:1b,Invulnerable:1b,NoGravity:1b,Marker:1b,CustomName:"torch"}
summon minecraft:armor_stand ~2.0 ~4.0 ~4.0 {Invisible:1b,Invulnerable:1b,NoGravity:1b,Marker:1b,CustomName:"torch"}
summon minecraft:armor_stand ~-1.0 ~ ~6.0 {Invisible:1b,Invulnerable:1b,NoGravity:1b,Marker:1b,CustomName:"torch"}
summon minecraft:armor_stand ~ ~-1.0 ~-5.5 {Invisible:1b,Invulnerable:1b,NoGravity:1b,Marker:1b,CustomName:"torch"}
summon minecraft:armor_stand ~2.0 ~-6.0 ~-1.0 {Invisible:1b,Invulnerable:1b,NoGravity:1b,Marker:1b,CustomName:"torch"}
summon minecraft:armor_stand ~ ~4.5 ~4.0 {Invisible:1b,Invulnerable:1b,NoGravity:1b,Marker:1b,CustomName:"torch"}
summon minecraft:armor_stand ~-6.0 ~-1.0 ~-2.0 {Invisible:1b,Invulnerable:1b,NoGravity:1b,Marker:1b,CustomName:"torch"}
summon minecraft:armor_stand ~5.0 ~2.0 ~-2.0 {Invisible:1b,Invulnerable:1b,NoGravity:1b,Marker:1b,CustomName:"torch"}
summon minecraft:armor_stand ~-1.0 ~6.0 ~1.0 {Invisible:1b,Invulnerable:1b,NoGravity:1b,Marker:1b,CustomName:"torch"}
summon minecraft:armor_stand ~ ~ ~6.5 {Invisible:1b,Invulnerable:1b,NoGravity:1b,Marker:1b,CustomName:"torch"}
summon minecraft:armor_stand ~1.0 ~ ~-6.0 {Invisible:1b,Invulnerable:1b,NoGravity:1b,Marker:1b,CustomName:"torch"}
summon minecraft:armor_stand ~-2.0 ~-2.0 ~-5.0 {Invisible:1b,Invulnerable:1b,NoGravity:1b,Marker:1b,CustomName:"torch"}
summon minecraft:armor_stand ~5.5 ~-1.0 ~3.0 {Invisible:1b,Invulnerable:1b,NoGravity:1b,Marker:1b,CustomName:"torch"}
summon minecraft:armor_stand ~2.0 ~1.0 ~-6.0 {Invisible:1b,Invulnerable:1b,NoGravity:1b,Marker:1b,CustomName:"torch"}
summon minecraft:armor_stand ~ ~-5.5 ~2.0 {Invisible:1b,Invulnerable:1b,NoGravity:1b,Marker:1b,CustomName:"torch"}
summon minecraft:armor_stand ~5.0 ~-2.0 ~2.0 {Invisible:1b,Invulnerable:1b,NoGravity:1b,Marker:1b,CustomName:"torch"}
summon minecraft:armor_stand ~-5.0 ~-2.0 ~2.0 {Invisible:1b,Invulnerable:1b,NoGravity:1b,Marker:1b,CustomName:"torch"}
summon minecraft:armor_stand ~2.0 ~-2.0 ~5.0 {Invisible:1b,Invulnerable:1b,NoGravity:1b,Marker:1b,CustomName:"torch"}
summon minecraft:armor_stand ~1.0 ~6.0 ~-2.0 {Invisible:1b,Invulnerable:1b,NoGravity:1b,Marker:1b,CustomName:"torch"}
summon minecraft:armor_stand ~5.0 ~-2.0 ~-2.0 {Invisible:1b,Invulnerable:1b,NoGravity:1b,Marker:1b,CustomName:"torch"}
summon minecraft:armor_stand ~6.0 ~-1.0 ~1.0 {Invisible:1b,Invulnerable:1b,NoGravity:1b,Marker:1b,CustomName:"torch"}
summon minecraft:armor_stand ~6.0 ~ ~2.0 {Invisible:1b,Invulnerable:1b,NoGravity:1b,Marker:1b,CustomName:"torch"}
summon minecraft:armor_stand ~-4.0 ~-5.0 ~1.0 {Invisible:1b,Invulnerable:1b,NoGravity:1b,Marker:1b,CustomName:"torch"}
summon minecraft:armor_stand ~-5.0 ~-1.0 ~4.0 {Invisible:1b,Invulnerable:1b,NoGravity:1b,Marker:1b,CustomName:"torch"}
summon minecraft:armor_stand ~2.0 ~5.0 ~-3.0 {Invisible:1b,Invulnerable:1b,NoGravity:1b,Marker:1b,CustomName:"torch"}
summon minecraft:armor_stand ~3.0 ~-1.0 ~-5.5 {Invisible:1b,Invulnerable:1b,NoGravity:1b,Marker:1b,CustomName:"torch"}
summon minecraft:armor_stand ~1.0 ~1.0 ~-6.0 {Invisible:1b,Invulnerable:1b,NoGravity:1b,Marker:1b,CustomName:"torch"}
summon minecraft:armor_stand ~-2.0 ~-2.0 ~5.0 {Invisible:1b,Invulnerable:1b,NoGravity:1b,Marker:1b,CustomName:"torch"}
summon minecraft:armor_stand ~1.0 ~-4.0 ~5.0 {Invisible:1b,Invulnerable:1b,NoGravity:1b,Marker:1b,CustomName:"torch"}
summon minecraft:armor_stand ~-3.0 ~-3.0 ~-4.5 {Invisible:1b,Invulnerable:1b,NoGravity:1b,Marker:1b,CustomName:"torch"}
summon minecraft:armor_stand ~-1.0 ~6.0 ~-2.0 {Invisible:1b,Invulnerable:1b,NoGravity:1b,Marker:1b,CustomName:"torch"}
summon minecraft:armor_stand ~-2.0 ~1.0 ~-6.0 {Invisible:1b,Invulnerable:1b,NoGravity:1b,Marker:1b,CustomName:"torch"}
summon minecraft:armor_stand ~-2.0 ~-3.0 ~-5.0 {Invisible:1b,Invulnerable:1b,NoGravity:1b,Marker:1b,CustomName:"torch"}
summon minecraft:armor_stand ~5.0 ~-3.0 ~-2.0 {Invisible:1b,Invulnerable:1b,NoGravity:1b,Marker:1b,CustomName:"torch"}
summon minecraft:armor_stand ~3.0 ~-5.5 ~ {Invisible:1b,Invulnerable:1b,NoGravity:1b,Marker:1b,CustomName:"torch"}
summon minecraft:armor_stand ~1.0 ~-5.0 ~-3.0 {Invisible:1b,Invulnerable:1b,NoGravity:1b,Marker:1b,CustomName:"torch"}
summon minecraft:armor_stand ~3.0 ~ ~-5.5 {Invisible:1b,Invulnerable:1b,NoGravity:1b,Marker:1b,CustomName:"torch"}
summon minecraft:armor_stand ~-4.0 ~-5.0 ~ {Invisible:1b,Invulnerable:1b,NoGravity:1b,Marker:1b,CustomName:"torch"}
summon minecraft:armor_stand ~-3.0 ~-5.5 ~1.0 {Invisible:1b,Invulnerable:1b,NoGravity:1b,Marker:1b,CustomName:"torch"}
summon minecraft:armor_stand ~2.0 ~-1.0 ~-6.0 {Invisible:1b,Invulnerable:1b,NoGravity:1b,Marker:1b,CustomName:"torch"}
summon minecraft:armor_stand ~-5.5 ~ ~3.0 {Invisible:1b,Invulnerable:1b,NoGravity:1b,Marker:1b,CustomName:"torch"}
summon minecraft:armor_stand ~-4.0 ~4.0 ~3.0 {Invisible:1b,Invulnerable:1b,NoGravity:1b,Marker:1b,CustomName:"torch"}
summon minecraft:armor_stand ~-1.0 ~3.0 ~-5.0 {Invisible:1b,Invulnerable:1b,NoGravity:1b,Marker:1b,CustomName:"torch"}
summon minecraft:armor_stand ~-1.0 ~2.0 ~-6.0 {Invisible:1b,Invulnerable:1b,NoGravity:1b,Marker:1b,CustomName:"torch"}
summon minecraft:armor_stand ~4.0 ~3.0 ~4.0 {Invisible:1b,Invulnerable:1b,NoGravity:1b,Marker:1b,CustomName:"torch"}
summon minecraft:armor_stand ~4.5 ~2.0 ~-3.0 {Invisible:1b,Invulnerable:1b,NoGravity:1b,Marker:1b,CustomName:"torch"}
summon minecraft:armor_stand ~2.0 ~ ~-6.0 {Invisible:1b,Invulnerable:1b,NoGravity:1b,Marker:1b,CustomName:"torch"}
summon minecraft:armor_stand ~-3.0 ~1.0 ~-5.5 {Invisible:1b,Invulnerable:1b,NoGravity:1b,Marker:1b,CustomName:"torch"}
summon minecraft:armor_stand ~ ~-4.5 ~-4.0 {Invisible:1b,Invulnerable:1b,NoGravity:1b,Marker:1b,CustomName:"torch"}
summon minecraft:armor_stand ~1.0 ~5.0 ~4.0 {Invisible:1b,Invulnerable:1b,NoGravity:1b,Marker:1b,CustomName:"torch"}
summon minecraft:armor_stand ~ ~-2.0 ~-5.5 {Invisible:1b,Invulnerable:1b,NoGravity:1b,Marker:1b,CustomName:"torch"}
summon minecraft:armor_stand ~4.5 ~3.0 ~3.0 {Invisible:1b,Invulnerable:1b,NoGravity:1b,Marker:1b,CustomName:"torch"}
summon minecraft:armor_stand ~-2.0 ~-4.0 ~4.0 {Invisible:1b,Invulnerable:1b,NoGravity:1b,Marker:1b,CustomName:"torch"}
summon minecraft:armor_stand ~-2.0 ~-6.0 ~1.0 {Invisible:1b,Invulnerable:1b,NoGravity:1b,Marker:1b,CustomName:"torch"}
summon minecraft:armor_stand ~-4.0 ~-1.0 ~-5.0 {Invisible:1b,Invulnerable:1b,NoGravity:1b,Marker:1b,CustomName:"torch"}
summon minecraft:armor_stand ~-3.0 ~2.0 ~-4.5 {Invisible:1b,Invulnerable:1b,NoGravity:1b,Marker:1b,CustomName:"torch"}
summon minecraft:armor_stand ~2.0 ~2.0 ~5.0 {Invisible:1b,Invulnerable:1b,NoGravity:1b,Marker:1b,CustomName:"torch"}
summon minecraft:armor_stand ~5.0 ~-3.0 ~-1.0 {Invisible:1b,Invulnerable:1b,NoGravity:1b,Marker:1b,CustomName:"torch"}
summon minecraft:armor_stand ~5.5 ~3.0 ~ {Invisible:1b,Invulnerable:1b,NoGravity:1b,Marker:1b,CustomName:"torch"}
summon minecraft:armor_stand ~1.0 ~-5.0 ~4.0 {Invisible:1b,Invulnerable:1b,NoGravity:1b,Marker:1b,CustomName:"torch"}
summon minecraft:armor_stand ~-6.0 ~1.0 ~-2.0 {Invisible:1b,Invulnerable:1b,NoGravity:1b,Marker:1b,CustomName:"torch"}
summon minecraft:armor_stand ~-5.0 ~-4.0 ~-1.0 {Invisible:1b,Invulnerable:1b,NoGravity:1b,Marker:1b,CustomName:"torch"}
summon minecraft:armor_stand ~3.0 ~-2.0 ~4.5 {Invisible:1b,Invulnerable:1b,NoGravity:1b,Marker:1b,CustomName:"torch"}
summon minecraft:armor_stand ~-3.0 ~-4.5 ~-3.0 {Invisible:1b,Invulnerable:1b,NoGravity:1b,Marker:1b,CustomName:"torch"}
summon minecraft:armor_stand ~ ~-5.5 ~-1.0 {Invisible:1b,Invulnerable:1b,NoGravity:1b,Marker:1b,CustomName:"torch"}
summon minecraft:armor_stand ~1.0 ~5.0 ~-4.0 {Invisible:1b,Invulnerable:1b,NoGravity:1b,Marker:1b,CustomName:"torch"}
summon minecraft:armor_stand ~1.0 ~ ~6.0 {Invisible:1b,Invulnerable:1b,NoGravity:1b,Marker:1b,CustomName:"torch"}
summon minecraft:armor_stand ~2.0 ~-4.0 ~-4.0 {Invisible:1b,Invulnerable:1b,NoGravity:1b,Marker:1b,CustomName:"torch"}
summon minecraft:armor_stand ~4.0 ~-4.0 ~3.0 {Invisible:1b,Invulnerable:1b,NoGravity:1b,Marker:1b,CustomName:"torch"}
summon minecraft:armor_stand ~-2.0 ~3.0 ~-5.0 {Invisible:1b,Invulnerable:1b,NoGravity:1b,Marker:1b,CustomName:"torch"}
summon minecraft:armor_stand ~-4.0 ~-3.0 ~4.0 {Invisible:1b,Invulnerable:1b,NoGravity:1b,Marker:1b,CustomName:"torch"}
summon minecraft:armor_stand ~-1.0 ~6.0 ~ {Invisible:1b,Invulnerable:1b,NoGravity:1b,Marker:1b,CustomName:"torch"}
summon minecraft:armor_stand ~5.0 ~-1.0 ~-4.0 {Invisible:1b,Invulnerable:1b,NoGravity:1b,Marker:1b,CustomName:"torch"}
summon minecraft:armor_stand ~-3.0 ~ ~-5.5 {Invisible:1b,Invulnerable:1b,NoGravity:1b,Marker:1b,CustomName:"torch"}
summon minecraft:armor_stand ~2.0 ~2.0 ~-5.0 {Invisible:1b,Invulnerable:1b,NoGravity:1b,Marker:1b,CustomName:"torch"}
summon minecraft:armor_stand ~6.0 ~ ~-2.0 {Invisible:1b,Invulnerable:1b,NoGravity:1b,Marker:1b,CustomName:"torch"}
summon minecraft:armor_stand ~1.0 ~6.0 ~ {Invisible:1b,Invulnerable:1b,NoGravity:1b,Marker:1b,CustomName:"torch"}
summon minecraft:armor_stand ~-2.0 ~-5.0 ~3.0 {Invisible:1b,Invulnerable:1b,NoGravity:1b,Marker:1b,CustomName:"torch"}
summon minecraft:armor_stand ~5.5 ~1.0 ~3.0 {Invisible:1b,Invulnerable:1b,NoGravity:1b,Marker:1b,CustomName:"torch"}
summon minecraft:armor_stand ~-5.0 ~ ~-4.0 {Invisible:1b,Invulnerable:1b,NoGravity:1b,Marker:1b,CustomName:"torch"}
summon minecraft:armor_stand ~-6.0 ~1.0 ~1.0 {Invisible:1b,Invulnerable:1b,NoGravity:1b,Marker:1b,CustomName:"torch"}
summon minecraft:armor_stand ~-1.0 ~2.0 ~6.0 {Invisible:1b,Invulnerable:1b,NoGravity:1b,Marker:1b,CustomName:"torch"}
summon minecraft:armor_stand ~-6.0 ~ ~-1.0 {Invisible:1b,Invulnerable:1b,NoGravity:1b,Marker:1b,CustomName:"torch"}
summon minecraft:armor_stand ~5.5 ~2.0 ~ {Invisible:1b,Invulnerable:1b,NoGravity:1b,Marker:1b,CustomName:"torch"}
summon minecraft:armor_stand ~-5.5 ~-2.0 ~ {Invisible:1b,Invulnerable:1b,NoGravity:1b,Marker:1b,CustomName:"torch"}
summon minecraft:armor_stand ~-4.0 ~4.0 ~2.0 {Invisible:1b,Invulnerable:1b,NoGravity:1b,Marker:1b,CustomName:"torch"}
summon minecraft:armor_stand ~4.0 ~-5.0 ~1.0 {Invisible:1b,Invulnerable:1b,NoGravity:1b,Marker:1b,CustomName:"torch"}
summon minecraft:armor_stand ~6.0 ~-2.0 ~-1.0 {Invisible:1b,Invulnerable:1b,NoGravity:1b,Marker:1b,CustomName:"torch"}
summon minecraft:armor_stand ~4.0 ~-2.0 ~-4.0 {Invisible:1b,Invulnerable:1b,NoGravity:1b,Marker:1b,CustomName:"torch"}
summon minecraft:armor_stand ~2.0 ~-3.0 ~5.0 {Invisible:1b,Invulnerable:1b,NoGravity:1b,Marker:1b,CustomName:"torch"}
summon minecraft:armor_stand ~-4.0 ~-2.0 ~4.0 {Invisible:1b,Invulnerable:1b,NoGravity:1b,Marker:1b,CustomName:"torch"}
summon minecraft:armor_stand ~4.0 ~2.0 ~-4.0 {Invisible:1b,Invulnerable:1b,NoGravity:1b,Marker:1b,CustomName:"torch"}
summon minecraft:armor_stand ~4.0 ~2.0 ~4.0 {Invisible:1b,Invulnerable:1b,NoGravity:1b,Marker:1b,CustomName:"torch"}
summon minecraft:armor_stand ~ ~-5.5 ~1.0 {Invisible:1b,Invulnerable:1b,NoGravity:1b,Marker:1b,CustomName:"torch"}
summon minecraft:armor_stand ~2.0 ~-5.0 ~-2.0 {Invisible:1b,Invulnerable:1b,NoGravity:1b,Marker:1b,CustomName:"torch"}
summon minecraft:armor_stand ~-3.0 ~-5.5 ~-1.0 {Invisible:1b,Invulnerable:1b,NoGravity:1b,Marker:1b,CustomName:"torch"}
summon minecraft:armor_stand ~ ~-2.0 ~5.5 {Invisible:1b,Invulnerable:1b,NoGravity:1b,Marker:1b,CustomName:"torch"}
summon minecraft:armor_stand ~3.0 ~1.0 ~-5.5 {Invisible:1b,Invulnerable:1b,NoGravity:1b,Marker:1b,CustomName:"torch"}
summon minecraft:armor_stand ~ ~1.0 ~5.5 {Invisible:1b,Invulnerable:1b,NoGravity:1b,Marker:1b,CustomName:"torch"}
summon minecraft:armor_stand ~5.5 ~-2.0 ~ {Invisible:1b,Invulnerable:1b,NoGravity:1b,Marker:1b,CustomName:"torch"}
summon minecraft:armor_stand ~-2.0 ~ ~6.0 {Invisible:1b,Invulnerable:1b,NoGravity:1b,Marker:1b,CustomName:"torch"}
summon minecraft:armor_stand ~5.0 ~3.0 ~-1.0 {Invisible:1b,Invulnerable:1b,NoGravity:1b,Marker:1b,CustomName:"torch"}
summon minecraft:armor_stand ~-6.0 ~-1.0 ~-1.0 {Invisible:1b,Invulnerable:1b,NoGravity:1b,Marker:1b,CustomName:"torch"}
summon minecraft:armor_stand ~ ~3.0 ~-5.5 {Invisible:1b,Invulnerable:1b,NoGravity:1b,Marker:1b,CustomName:"torch"}
summon minecraft:armor_stand ~-3.0 ~4.5 ~-3.0 {Invisible:1b,Invulnerable:1b,NoGravity:1b,Marker:1b,CustomName:"torch"}
summon minecraft:armor_stand ~-6.0 ~1.0 ~-1.0 {Invisible:1b,Invulnerable:1b,NoGravity:1b,Marker:1b,CustomName:"torch"}
summon minecraft:armor_stand ~-2.0 ~5.0 ~-3.0 {Invisible:1b,Invulnerable:1b,NoGravity:1b,Marker:1b,CustomName:"torch"}
summon minecraft:armor_stand ~-4.0 ~ ~-5.0 {Invisible:1b,Invulnerable:1b,NoGravity:1b,Marker:1b,CustomName:"torch"}
summon minecraft:armor_stand ~3.0 ~4.5 ~-3.0 {Invisible:1b,Invulnerable:1b,NoGravity:1b,Marker:1b,CustomName:"torch"}
summon minecraft:armor_stand ~-3.0 ~3.0 ~4.5 {Invisible:1b,Invulnerable:1b,NoGravity:1b,Marker:1b,CustomName:"torch"}
summon minecraft:armor_stand ~ ~-5.5 ~3.0 {Invisible:1b,Invulnerable:1b,NoGravity:1b,Marker:1b,CustomName:"torch"}
summon minecraft:armor_stand ~ ~-3.0 ~-5.5 {Invisible:1b,Invulnerable:1b,NoGravity:1b,Marker:1b,CustomName:"torch"}
summon minecraft:armor_stand ~ ~-1.0 ~5.5 {Invisible:1b,Invulnerable:1b,NoGravity:1b,Marker:1b,CustomName:"torch"}
summon minecraft:armor_stand ~ ~1.0 ~-5.5 {Invisible:1b,Invulnerable:1b,NoGravity:1b,Marker:1b,CustomName:"torch"}
summon minecraft:armor_stand ~-2.0 ~6.0 ~1.0 {Invisible:1b,Invulnerable:1b,NoGravity:1b,Marker:1b,CustomName:"torch"}
summon minecraft:armor_stand ~-5.0 ~-2.0 ~-2.0 {Invisible:1b,Invulnerable:1b,NoGravity:1b,Marker:1b,CustomName:"torch"}
summon minecraft:armor_stand ~-6.0 ~2.0 ~1.0 {Invisible:1b,Invulnerable:1b,NoGravity:1b,Marker:1b,CustomName:"torch"}
summon minecraft:armor_stand ~3.0 ~-1.0 ~5.5 {Invisible:1b,Invulnerable:1b,NoGravity:1b,Marker:1b,CustomName:"torch"}
summon minecraft:armor_stand ~6.0 ~-1.0 ~-2.0 {Invisible:1b,Invulnerable:1b,NoGravity:1b,Marker:1b,CustomName:"torch"}
summon minecraft:armor_stand ~-5.5 ~-1.0 ~3.0 {Invisible:1b,Invulnerable:1b,NoGravity:1b,Marker:1b,CustomName:"torch"}
summon minecraft:armor_stand ~4.0 ~4.0 ~-2.0 {Invisible:1b,Invulnerable:1b,NoGravity:1b,Marker:1b,CustomName:"torch"}
summon minecraft:armor_stand ~4.0 ~-3.0 ~-4.0 {Invisible:1b,Invulnerable:1b,NoGravity:1b,Marker:1b,CustomName:"torch"}
summon minecraft:armor_stand ~5.5 ~-3.0 ~ {Invisible:1b,Invulnerable:1b,NoGravity:1b,Marker:1b,CustomName:"torch"}
summon minecraft:armor_stand ~3.0 ~1.0 ~5.5 {Invisible:1b,Invulnerable:1b,NoGravity:1b,Marker:1b,CustomName:"torch"}
summon minecraft:armor_stand ~-4.5 ~4.0 ~ {Invisible:1b,Invulnerable:1b,NoGravity:1b,Marker:1b,CustomName:"torch"}
summon minecraft:armor_stand ~-1.0 ~5.0 ~-3.0 {Invisible:1b,Invulnerable:1b,NoGravity:1b,Marker:1b,CustomName:"torch"}
summon minecraft:armor_stand ~-6.0 ~2.0 ~-1.0 {Invisible:1b,Invulnerable:1b,NoGravity:1b,Marker:1b,CustomName:"torch"}
summon minecraft:armor_stand ~-5.0 ~-3.0 ~1.0 {Invisible:1b,Invulnerable:1b,NoGravity:1b,Marker:1b,CustomName:"torch"}
summon minecraft:armor_stand ~-2.0 ~-4.0 ~-4.0 {Invisible:1b,Invulnerable:1b,NoGravity:1b,Marker:1b,CustomName:"torch"}
summon minecraft:armor_stand ~ ~3.0 ~5.5 {Invisible:1b,Invulnerable:1b,NoGravity:1b,Marker:1b,CustomName:"torch"}
summon minecraft:armor_stand ~-4.0 ~4.0 ~-2.0 {Invisible:1b,Invulnerable:1b,NoGravity:1b,Marker:1b,CustomName:"torch"}
summon minecraft:armor_stand ~3.0 ~-3.0 ~-4.5 {Invisible:1b,Invulnerable:1b,NoGravity:1b,Marker:1b,CustomName:"torch"}
summon minecraft:armor_stand ~5.0 ~2.0 ~2.0 {Invisible:1b,Invulnerable:1b,NoGravity:1b,Marker:1b,CustomName:"torch"}
summon minecraft:armor_stand ~-1.0 ~5.0 ~4.0 {Invisible:1b,Invulnerable:1b,NoGravity:1b,Marker:1b,CustomName:"torch"}
summon minecraft:armor_stand ~1.0 ~-1.0 ~-6.0 {Invisible:1b,Invulnerable:1b,NoGravity:1b,Marker:1b,CustomName:"torch"}
summon minecraft:armor_stand ~3.0 ~2.0 ~-4.5 {Invisible:1b,Invulnerable:1b,NoGravity:1b,Marker:1b,CustomName:"torch"}
summon minecraft:armor_stand ~4.0 ~4.0 ~3.0 {Invisible:1b,Invulnerable:1b,NoGravity:1b,Marker:1b,CustomName:"torch"}
summon minecraft:armor_stand ~-4.5 ~-2.0 ~3.0 {Invisible:1b,Invulnerable:1b,NoGravity:1b,Marker:1b,CustomName:"torch"}
summon minecraft:armor_stand ~4.5 ~-2.0 ~3.0 {Invisible:1b,Invulnerable:1b,NoGravity:1b,Marker:1b,CustomName:"torch"}
summon minecraft:armor_stand ~1.0 ~6.0 ~-1.0 {Invisible:1b,Invulnerable:1b,NoGravity:1b,Marker:1b,CustomName:"torch"}
summon minecraft:armor_stand ~-3.0 ~-2.0 ~4.5 {Invisible:1b,Invulnerable:1b,NoGravity:1b,Marker:1b,CustomName:"torch"}
summon minecraft:armor_stand ~-2.0 ~4.0 ~4.0 {Invisible:1b,Invulnerable:1b,NoGravity:1b,Marker:1b,CustomName:"torch"}
summon minecraft:armor_stand ~4.5 ~-2.0 ~-3.0 {Invisible:1b,Invulnerable:1b,NoGravity:1b,Marker:1b,CustomName:"torch"}
summon minecraft:armor_stand ~6.0 ~1.0 ~2.0 {Invisible:1b,Invulnerable:1b,NoGravity:1b,Marker:1b,CustomName:"torch"}
summon minecraft:armor_stand ~2.0 ~5.0 ~-2.0 {Invisible:1b,Invulnerable:1b,NoGravity:1b,Marker:1b,CustomName:"torch"}
summon minecraft:armor_stand ~ ~-4.0 ~4.5 {Invisible:1b,Invulnerable:1b,NoGravity:1b,Marker:1b,CustomName:"torch"}
summon minecraft:armor_stand ~3.0 ~-4.5 ~3.0 {Invisible:1b,Invulnerable:1b,NoGravity:1b,Marker:1b,CustomName:"torch"}
summon minecraft:armor_stand ~-4.5 ~-2.0 ~-3.0 {Invisible:1b,Invulnerable:1b,NoGravity:1b,Marker:1b,CustomName:"torch"}
summon minecraft:armor_stand ~-5.0 ~3.0 ~-1.0 {Invisible:1b,Invulnerable:1b,NoGravity:1b,Marker:1b,CustomName:"torch"}
summon minecraft:armor_stand ~-4.0 ~-2.0 ~-4.0 {Invisible:1b,Invulnerable:1b,NoGravity:1b,Marker:1b,CustomName:"torch"}
summon minecraft:armor_stand ~-2.0 ~2.0 ~5.0 {Invisible:1b,Invulnerable:1b,NoGravity:1b,Marker:1b,CustomName:"torch"}
summon minecraft:armor_stand ~4.0 ~1.0 ~-5.0 {Invisible:1b,Invulnerable:1b,NoGravity:1b,Marker:1b,CustomName:"torch"}
summon minecraft:armor_stand ~-2.0 ~5.0 ~2.0 {Invisible:1b,Invulnerable:1b,NoGravity:1b,Marker:1b,CustomName:"torch"}
summon minecraft:armor_stand ~-4.5 ~-3.0 ~-3.0 {Invisible:1b,Invulnerable:1b,NoGravity:1b,Marker:1b,CustomName:"torch"}
summon minecraft:armor_stand ~-4.0 ~5.0 ~-1.0 {Invisible:1b,Invulnerable:1b,NoGravity:1b,Marker:1b,CustomName:"torch"}
summon minecraft:armor_stand ~3.0 ~5.5 ~ {Invisible:1b,Invulnerable:1b,NoGravity:1b,Marker:1b,CustomName:"torch"}
summon minecraft:armor_stand ~-5.5 ~-3.0 ~ {Invisible:1b,Invulnerable:1b,NoGravity:1b,Marker:1b,CustomName:"torch"}
summon minecraft:armor_stand ~5.0 ~3.0 ~-2.0 {Invisible:1b,Invulnerable:1b,NoGravity:1b,Marker:1b,CustomName:"torch"}
summon minecraft:armor_stand ~-3.0 ~-2.0 ~-4.5 {Invisible:1b,Invulnerable:1b,NoGravity:1b,Marker:1b,CustomName:"torch"}
summon minecraft:armor_stand ~ ~-4.0 ~-4.5 {Invisible:1b,Invulnerable:1b,NoGravity:1b,Marker:1b,CustomName:"torch"}
summon minecraft:armor_stand ~-4.5 ~-3.0 ~3.0 {Invisible:1b,Invulnerable:1b,NoGravity:1b,Marker:1b,CustomName:"torch"}
summon minecraft:armor_stand ~-4.0 ~4.0 ~-3.0 {Invisible:1b,Invulnerable:1b,NoGravity:1b,Marker:1b,CustomName:"torch"}
summon minecraft:armor_stand ~-1.0 ~-6.0 ~ {Invisible:1b,Invulnerable:1b,NoGravity:1b,Marker:1b,CustomName:"torch"}
summon minecraft:armor_stand ~-6.0 ~ ~-2.0 {Invisible:1b,Invulnerable:1b,NoGravity:1b,Marker:1b,CustomName:"torch"}
summon minecraft:armor_stand ~4.0 ~-4.0 ~-3.0 {Invisible:1b,Invulnerable:1b,NoGravity:1b,Marker:1b,CustomName:"torch"}
summon minecraft:armor_stand ~3.0 ~3.0 ~-4.5 {Invisible:1b,Invulnerable:1b,NoGravity:1b,Marker:1b,CustomName:"torch"}
summon minecraft:armor_stand ~1.0 ~-6.0 ~-2.0 {Invisible:1b,Invulnerable:1b,NoGravity:1b,Marker:1b,CustomName:"torch"}
summon minecraft:armor_stand ~ ~-5.5 ~-2.0 {Invisible:1b,Invulnerable:1b,NoGravity:1b,Marker:1b,CustomName:"torch"}
summon minecraft:armor_stand ~ ~4.0 ~-4.5 {Invisible:1b,Invulnerable:1b,NoGravity:1b,Marker:1b,CustomName:"torch"}
summon minecraft:armor_stand ~6.0 ~2.0 ~-1.0 {Invisible:1b,Invulnerable:1b,NoGravity:1b,Marker:1b,CustomName:"torch"}
summon minecraft:armor_stand ~5.0 ~3.0 ~1.0 {Invisible:1b,Invulnerable:1b,NoGravity:1b,Marker:1b,CustomName:"torch"}
summon minecraft:armor_stand ~-1.0 ~-3.0 ~-5.0 {Invisible:1b,Invulnerable:1b,NoGravity:1b,Marker:1b,CustomName:"torch"}
summon minecraft:armor_stand ~3.0 ~-5.5 ~1.0 {Invisible:1b,Invulnerable:1b,NoGravity:1b,Marker:1b,CustomName:"torch"}
summon minecraft:armor_stand ~3.0 ~5.5 ~-1.0 {Invisible:1b,Invulnerable:1b,NoGravity:1b,Marker:1b,CustomName:"torch"}
summon minecraft:armor_stand ~ ~4.0 ~4.5 {Invisible:1b,Invulnerable:1b,NoGravity:1b,Marker:1b,CustomName:"torch"}
summon minecraft:armor_stand ~-1.0 ~-5.0 ~-3.0 {Invisible:1b,Invulnerable:1b,NoGravity:1b,Marker:1b,CustomName:"torch"}
summon minecraft:armor_stand ~-4.0 ~-4.0 ~3.0 {Invisible:1b,Invulnerable:1b,NoGravity:1b,Marker:1b,CustomName:"torch"}
summon minecraft:armor_stand ~1.0 ~-2.0 ~6.0 {Invisible:1b,Invulnerable:1b,NoGravity:1b,Marker:1b,CustomName:"torch"}
summon minecraft:armor_stand ~-1.0 ~-6.0 ~2.0 {Invisible:1b,Invulnerable:1b,NoGravity:1b,Marker:1b,CustomName:"torch"}
summon minecraft:armor_stand ~1.0 ~6.0 ~2.0 {Invisible:1b,Invulnerable:1b,NoGravity:1b,Marker:1b,CustomName:"torch"}
summon minecraft:armor_stand ~-1.0 ~-6.0 ~-2.0 {Invisible:1b,Invulnerable:1b,NoGravity:1b,Marker:1b,CustomName:"torch"}
summon minecraft:armor_stand ~-6.0 ~1.0 ~2.0 {Invisible:1b,Invulnerable:1b,NoGravity:1b,Marker:1b,CustomName:"torch"}
summon minecraft:armor_stand ~-4.5 ~3.0 ~-3.0 {Invisible:1b,Invulnerable:1b,NoGravity:1b,Marker:1b,CustomName:"torch"}
summon minecraft:armor_stand ~-4.0 ~2.0 ~4.0 {Invisible:1b,Invulnerable:1b,NoGravity:1b,Marker:1b,CustomName:"torch"}
summon minecraft:armor_stand ~3.0 ~4.5 ~2.0 {Invisible:1b,Invulnerable:1b,NoGravity:1b,Marker:1b,CustomName:"torch"}
summon minecraft:armor_stand ~4.5 ~-3.0 ~-3.0 {Invisible:1b,Invulnerable:1b,NoGravity:1b,Marker:1b,CustomName:"torch"}
summon minecraft:armor_stand ~-3.0 ~3.0 ~-4.5 {Invisible:1b,Invulnerable:1b,NoGravity:1b,Marker:1b,CustomName:"torch"}
summon minecraft:armor_stand ~2.0 ~6.0 ~-1.0 {Invisible:1b,Invulnerable:1b,NoGravity:1b,Marker:1b,CustomName:"torch"}
summon minecraft:armor_stand ~-1.0 ~4.0 ~5.0 {Invisible:1b,Invulnerable:1b,NoGravity:1b,Marker:1b,CustomName:"torch"}
summon minecraft:armor_stand ~-3.0 ~-4.5 ~2.0 {Invisible:1b,Invulnerable:1b,NoGravity:1b,Marker:1b,CustomName:"torch"}
summon minecraft:armor_stand ~6.0 ~1.0 ~-1.0 {Invisible:1b,Invulnerable:1b,NoGravity:1b,Marker:1b,CustomName:"torch"}
summon minecraft:armor_stand ~2.0 ~5.0 ~3.0 {Invisible:1b,Invulnerable:1b,NoGravity:1b,Marker:1b,CustomName:"torch"}
summon minecraft:armor_stand ~-5.0 ~4.0 ~-1.0 {Invisible:1b,Invulnerable:1b,NoGravity:1b,Marker:1b,CustomName:"torch"}
summon minecraft:armor_stand ~-2.0 ~-5.0 ~2.0 {Invisible:1b,Invulnerable:1b,NoGravity:1b,Marker:1b,CustomName:"torch"}
summon minecraft:armor_stand ~-2.0 ~-6.0 ~ {Invisible:1b,Invulnerable:1b,NoGravity:1b,Marker:1b,CustomName:"torch"}
summon minecraft:armor_stand ~1.0 ~4.0 ~-5.0 {Invisible:1b,Invulnerable:1b,NoGravity:1b,Marker:1b,CustomName:"torch"}
summon minecraft:armor_stand ~4.5 ~3.0 ~-3.0 {Invisible:1b,Invulnerable:1b,NoGravity:1b,Marker:1b,CustomName:"torch"}
summon minecraft:armor_stand ~-4.0 ~-5.0 ~-1.0 {Invisible:1b,Invulnerable:1b,NoGravity:1b,Marker:1b,CustomName:"torch"}
summon minecraft:armor_stand ~4.0 ~3.0 ~-4.0 {Invisible:1b,Invulnerable:1b,NoGravity:1b,Marker:1b,CustomName:"torch"}
summon minecraft:armor_stand ~6.0 ~ ~1.0 {Invisible:1b,Invulnerable:1b,NoGravity:1b,Marker:1b,CustomName:"torch"}
summon minecraft:armor_stand ~1.0 ~5.0 ~3.0 {Invisible:1b,Invulnerable:1b,NoGravity:1b,Marker:1b,CustomName:"torch"}
summon minecraft:armor_stand ~-3.0 ~1.0 ~5.5 {Invisible:1b,Invulnerable:1b,NoGravity:1b,Marker:1b,CustomName:"torch"}
summon minecraft:armor_stand ~4.0 ~-2.0 ~4.0 {Invisible:1b,Invulnerable:1b,NoGravity:1b,Marker:1b,CustomName:"torch"}
summon minecraft:armor_stand ~-5.0 ~-4.0 ~1.0 {Invisible:1b,Invulnerable:1b,NoGravity:1b,Marker:1b,CustomName:"torch"}
summon minecraft:armor_stand ~2.0 ~6.0 ~ {Invisible:1b,Invulnerable:1b,NoGravity:1b,Marker:1b,CustomName:"torch"}
summon minecraft:armor_stand ~2.0 ~5.0 ~2.0 {Invisible:1b,Invulnerable:1b,NoGravity:1b,Marker:1b,CustomName:"torch"}
summon minecraft:armor_stand ~-1.0 ~1.0 ~-6.0 {Invisible:1b,Invulnerable:1b,NoGravity:1b,Marker:1b,CustomName:"torch"}
summon minecraft:armor_stand ~-2.0 ~-1.0 ~6.0 {Invisible:1b,Invulnerable:1b,NoGravity:1b,Marker:1b,CustomName:"torch"}
summon minecraft:armor_stand ~-5.0 ~-1.0 ~-4.0 {Invisible:1b,Invulnerable:1b,NoGravity:1b,Marker:1b,CustomName:"torch"}
summon minecraft:armor_stand ~ ~-5.5 ~-3.0 {Invisible:1b,Invulnerable:1b,NoGravity:1b,Marker:1b,CustomName:"torch"}
summon minecraft:armor_stand ~-1.0 ~5.0 ~-4.0 {Invisible:1b,Invulnerable:1b,NoGravity:1b,Marker:1b,CustomName:"torch"}
summon minecraft:armor_stand ~1.0 ~-3.0 ~5.0 {Invisible:1b,Invulnerable:1b,NoGravity:1b,Marker:1b,CustomName:"torch"}
summon minecraft:armor_stand ~1.0 ~3.0 ~-5.0 {Invisible:1b,Invulnerable:1b,NoGravity:1b,Marker:1b,CustomName:"torch"}
summon minecraft:armor_stand ~-4.0 ~5.0 ~1.0 {Invisible:1b,Invulnerable:1b,NoGravity:1b,Marker:1b,CustomName:"torch"}
summon minecraft:armor_stand ~-4.0 ~-3.0 ~-4.0 {Invisible:1b,Invulnerable:1b,NoGravity:1b,Marker:1b,CustomName:"torch"}
summon minecraft:armor_stand ~-1.0 ~-2.0 ~6.0 {Invisible:1b,Invulnerable:1b,NoGravity:1b,Marker:1b,CustomName:"torch"}
summon minecraft:armor_stand ~-1.0 ~-5.0 ~3.0 {Invisible:1b,Invulnerable:1b,NoGravity:1b,Marker:1b,CustomName:"torch"}
summon minecraft:armor_stand ~5.5 ~1.0 ~-3.0 {Invisible:1b,Invulnerable:1b,NoGravity:1b,Marker:1b,CustomName:"torch"}
summon minecraft:armor_stand ~-4.0 ~3.0 ~4.0 {Invisible:1b,Invulnerable:1b,NoGravity:1b,Marker:1b,CustomName:"torch"}
summon minecraft:armor_stand ~4.5 ~2.0 ~3.0 {Invisible:1b,Invulnerable:1b,NoGravity:1b,Marker:1b,CustomName:"torch"}
summon minecraft:armor_stand ~3.0 ~4.5 ~3.0 {Invisible:1b,Invulnerable:1b,NoGravity:1b,Marker:1b,CustomName:"torch"}
summon minecraft:armor_stand ~5.5 ~ ~-3.0 {Invisible:1b,Invulnerable:1b,NoGravity:1b,Marker:1b,CustomName:"torch"}
summon minecraft:armor_stand ~-2.0 ~-5.0 ~-2.0 {Invisible:1b,Invulnerable:1b,NoGravity:1b,Marker:1b,CustomName:"torch"}
summon minecraft:armor_stand ~6.0 ~-2.0 ~1.0 {Invisible:1b,Invulnerable:1b,NoGravity:1b,Marker:1b,CustomName:"torch"}
summon minecraft:armor_stand ~-6.0 ~ ~2.0 {Invisible:1b,Invulnerable:1b,NoGravity:1b,Marker:1b,CustomName:"torch"}
summon minecraft:armor_stand ~2.0 ~-4.0 ~4.0 {Invisible:1b,Invulnerable:1b,NoGravity:1b,Marker:1b,CustomName:"torch"}
summon minecraft:armor_stand ~5.0 ~ ~-4.0 {Invisible:1b,Invulnerable:1b,NoGravity:1b,Marker:1b,CustomName:"torch"}
summon minecraft:armor_stand ~3.0 ~5.5 ~1.0 {Invisible:1b,Invulnerable:1b,NoGravity:1b,Marker:1b,CustomName:"torch"}
summon minecraft:armor_stand ~-1.0 ~6.0 ~2.0 {Invisible:1b,Invulnerable:1b,NoGravity:1b,Marker:1b,CustomName:"torch"}
summon minecraft:armor_stand ~-2.0 ~-5.0 ~-3.0 {Invisible:1b,Invulnerable:1b,NoGravity:1b,Marker:1b,CustomName:"torch"}
summon minecraft:armor_stand ~-3.0 ~4.5 ~3.0 {Invisible:1b,Invulnerable:1b,NoGravity:1b,Marker:1b,CustomName:"torch"}
summon minecraft:armor_stand ~1.0 ~-5.0 ~3.0 {Invisible:1b,Invulnerable:1b,NoGravity:1b,Marker:1b,CustomName:"torch"}
summon minecraft:armor_stand ~4.0 ~-1.0 ~-5.0 {Invisible:1b,Invulnerable:1b,NoGravity:1b,Marker:1b,CustomName:"torch"}
summon minecraft:armor_stand ~ ~-6.5 ~ {Invisible:1b,Invulnerable:1b,NoGravity:1b,Marker:1b,CustomName:"torch"}
summon minecraft:armor_stand ~1.0 ~-1.0 ~6.0 {Invisible:1b,Invulnerable:1b,NoGravity:1b,Marker:1b,CustomName:"torch"}
summon minecraft:armor_stand ~1.0 ~1.0 ~6.0 {Invisible:1b,Invulnerable:1b,NoGravity:1b,Marker:1b,CustomName:"torch"}
summon minecraft:armor_stand ~-1.0 ~-1.0 ~6.0 {Invisible:1b,Invulnerable:1b,NoGravity:1b,Marker:1b,CustomName:"torch"}
summon minecraft:armor_stand ~5.0 ~-3.0 ~2.0 {Invisible:1b,Invulnerable:1b,NoGravity:1b,Marker:1b,CustomName:"torch"}
summon minecraft:armor_stand ~4.0 ~ ~5.0 {Invisible:1b,Invulnerable:1b,NoGravity:1b,Marker:1b,CustomName:"torch"}
summon minecraft:armor_stand ~-6.0 ~-1.0 ~2.0 {Invisible:1b,Invulnerable:1b,NoGravity:1b,Marker:1b,CustomName:"torch"}
summon minecraft:armor_stand ~1.0 ~2.0 ~-6.0 {Invisible:1b,Invulnerable:1b,NoGravity:1b,Marker:1b,CustomName:"torch"}
summon minecraft:armor_stand ~1.0 ~-5.0 ~-4.0 {Invisible:1b,Invulnerable:1b,NoGravity:1b,Marker:1b,CustomName:"torch"}
summon minecraft:armor_stand ~6.0 ~1.0 ~1.0 {Invisible:1b,Invulnerable:1b,NoGravity:1b,Marker:1b,CustomName:"torch"}
summon minecraft:armor_stand ~-2.0 ~5.0 ~3.0 {Invisible:1b,Invulnerable:1b,NoGravity:1b,Marker:1b,CustomName:"torch"}
summon minecraft:armor_stand ~-6.0 ~ ~1.0 {Invisible:1b,Invulnerable:1b,NoGravity:1b,Marker:1b,CustomName:"torch"}
summon minecraft:armor_stand ~-2.0 ~-3.0 ~5.0 {Invisible:1b,Invulnerable:1b,NoGravity:1b,Marker:1b,CustomName:"torch"}
summon minecraft:armor_stand ~-5.5 ~-1.0 ~ {Invisible:1b,Invulnerable:1b,NoGravity:1b,Marker:1b,CustomName:"torch"}
summon minecraft:armor_stand ~-4.0 ~3.0 ~-4.0 {Invisible:1b,Invulnerable:1b,NoGravity:1b,Marker:1b,CustomName:"torch"}
summon minecraft:armor_stand ~-3.0 ~-3.0 ~4.5 {Invisible:1b,Invulnerable:1b,NoGravity:1b,Marker:1b,CustomName:"torch"}
summon minecraft:armor_stand ~4.0 ~1.0 ~5.0 {Invisible:1b,Invulnerable:1b,NoGravity:1b,Marker:1b,CustomName:"torch"}
summon minecraft:armor_stand ~5.0 ~3.0 ~2.0 {Invisible:1b,Invulnerable:1b,NoGravity:1b,Marker:1b,CustomName:"torch"}
summon minecraft:armor_stand ~-4.5 ~2.0 ~-3.0 {Invisible:1b,Invulnerable:1b,NoGravity:1b,Marker:1b,CustomName:"torch"}
summon minecraft:armor_stand ~-4.5 ~2.0 ~3.0 {Invisible:1b,Invulnerable:1b,NoGravity:1b,Marker:1b,CustomName:"torch"}
summon minecraft:armor_stand ~-4.0 ~-4.0 ~2.0 {Invisible:1b,Invulnerable:1b,NoGravity:1b,Marker:1b,CustomName:"torch"}
summon minecraft:armor_stand ~1.0 ~-6.0 ~-1.0 {Invisible:1b,Invulnerable:1b,NoGravity:1b,Marker:1b,CustomName:"torch"}
summon minecraft:armor_stand ~3.0 ~ ~5.5 {Invisible:1b,Invulnerable:1b,NoGravity:1b,Marker:1b,CustomName:"torch"}
summon minecraft:armor_stand ~-1.0 ~-2.0 ~-6.0 {Invisible:1b,Invulnerable:1b,NoGravity:1b,Marker:1b,CustomName:"torch"}
summon minecraft:armor_stand ~-3.0 ~2.0 ~4.5 {Invisible:1b,Invulnerable:1b,NoGravity:1b,Marker:1b,CustomName:"torch"}
summon minecraft:armor_stand ~-2.0 ~3.0 ~5.0 {Invisible:1b,Invulnerable:1b,NoGravity:1b,Marker:1b,CustomName:"torch"}
summon minecraft:armor_stand ~6.0 ~1.0 ~-2.0 {Invisible:1b,Invulnerable:1b,NoGravity:1b,Marker:1b,CustomName:"torch"}
summon minecraft:armor_stand ~5.0 ~1.0 ~4.0 {Invisible:1b,Invulnerable:1b,NoGravity:1b,Marker:1b,CustomName:"torch"}
summon minecraft:armor_stand ~-1.0 ~-3.0 ~5.0 {Invisible:1b,Invulnerable:1b,NoGravity:1b,Marker:1b,CustomName:"torch"}
summon minecraft:armor_stand ~5.5 ~-1.0 ~-3.0 {Invisible:1b,Invulnerable:1b,NoGravity:1b,Marker:1b,CustomName:"torch"}
summon minecraft:armor_stand ~5.0 ~-4.0 ~-1.0 {Invisible:1b,Invulnerable:1b,NoGravity:1b,Marker:1b,CustomName:"torch"}
summon minecraft:armor_stand ~2.0 ~-6.0 ~1.0 {Invisible:1b,Invulnerable:1b,NoGravity:1b,Marker:1b,CustomName:"torch"}
summon minecraft:armor_stand ~-5.5 ~1.0 ~-3.0 {Invisible:1b,Invulnerable:1b,NoGravity:1b,Marker:1b,CustomName:"torch"}
summon minecraft:armor_stand ~4.0 ~5.0 ~1.0 {Invisible:1b,Invulnerable:1b,NoGravity:1b,Marker:1b,CustomName:"torch"}
summon minecraft:armor_stand ~ ~2.0 ~-5.5 {Invisible:1b,Invulnerable:1b,NoGravity:1b,Marker:1b,CustomName:"torch"}
summon minecraft:armor_stand ~4.5 ~-4.0 ~ {Invisible:1b,Invulnerable:1b,NoGravity:1b,Marker:1b,CustomName:"torch"}
summon minecraft:armor_stand ~-1.0 ~-4.0 ~-5.0 {Invisible:1b,Invulnerable:1b,NoGravity:1b,Marker:1b,CustomName:"torch"}
summon minecraft:armor_stand ~ ~2.0 ~5.5 {Invisible:1b,Invulnerable:1b,NoGravity:1b,Marker:1b,CustomName:"torch"}
summon minecraft:armor_stand ~4.5 ~4.0 ~ {Invisible:1b,Invulnerable:1b,NoGravity:1b,Marker:1b,CustomName:"torch"}
summon minecraft:armor_stand ~1.0 ~-3.0 ~-5.0 {Invisible:1b,Invulnerable:1b,NoGravity:1b,Marker:1b,CustomName:"torch"}
summon minecraft:armor_stand ~-6.5 ~ ~ {Invisible:1b,Invulnerable:1b,NoGravity:1b,Marker:1b,CustomName:"torch"}
summon minecraft:armor_stand ~-1.0 ~-1.0 ~-6.0 {Invisible:1b,Invulnerable:1b,NoGravity:1b,Marker:1b,CustomName:"torch"}
summon minecraft:armor_stand ~-2.0 ~-6.0 ~-1.0 {Invisible:1b,Invulnerable:1b,NoGravity:1b,Marker:1b,CustomName:"torch"}
summon minecraft:armor_stand ~-2.0 ~2.0 ~-5.0 {Invisible:1b,Invulnerable:1b,NoGravity:1b,Marker:1b,CustomName:"torch"}
summon minecraft:armor_stand ~3.0 ~-4.5 ~-3.0 {Invisible:1b,Invulnerable:1b,NoGravity:1b,Marker:1b,CustomName:"torch"}
summon minecraft:armor_stand ~4.0 ~4.0 ~-3.0 {Invisible:1b,Invulnerable:1b,NoGravity:1b,Marker:1b,CustomName:"torch"}
summon minecraft:armor_stand ~-1.0 ~5.0 ~3.0 {Invisible:1b,Invulnerable:1b,NoGravity:1b,Marker:1b,CustomName:"torch"}
summon minecraft:armor_stand ~-5.5 ~2.0 ~ {Invisible:1b,Invulnerable:1b,NoGravity:1b,Marker:1b,CustomName:"torch"}
summon minecraft:armor_stand ~-3.0 ~-4.5 ~3.0 {Invisible:1b,Invulnerable:1b,NoGravity:1b,Marker:1b,CustomName:"torch"}
summon minecraft:armor_stand ~-1.0 ~1.0 ~6.0 {Invisible:1b,Invulnerable:1b,NoGravity:1b,Marker:1b,CustomName:"torch"}
summon minecraft:armor_stand ~-5.0 ~3.0 ~2.0 {Invisible:1b,Invulnerable:1b,NoGravity:1b,Marker:1b,CustomName:"torch"}
summon minecraft:armor_stand ~-6.0 ~-2.0 ~1.0 {Invisible:1b,Invulnerable:1b,NoGravity:1b,Marker:1b,CustomName:"torch"}
summon minecraft:armor_stand ~1.0 ~2.0 ~6.0 {Invisible:1b,Invulnerable:1b,NoGravity:1b,Marker:1b,CustomName:"torch"}
summon minecraft:armor_stand ~4.0 ~-1.0 ~5.0 {Invisible:1b,Invulnerable:1b,NoGravity:1b,Marker:1b,CustomName:"torch"}
summon minecraft:armor_stand ~5.0 ~1.0 ~-4.0 {Invisible:1b,Invulnerable:1b,NoGravity:1b,Marker:1b,CustomName:"torch"}
summon minecraft:armor_stand ~-3.0 ~5.5 ~1.0 {Invisible:1b,Invulnerable:1b,NoGravity:1b,Marker:1b,CustomName:"torch"}
summon minecraft:armor_stand ~ ~ ~-6.5 {Invisible:1b,Invulnerable:1b,NoGravity:1b,Marker:1b,CustomName:"torch"}
summon minecraft:armor_stand ~5.0 ~4.0 ~1.0 {Invisible:1b,Invulnerable:1b,NoGravity:1b,Marker:1b,CustomName:"torch"}
summon minecraft:armor_stand ~5.0 ~4.0 ~-1.0 {Invisible:1b,Invulnerable:1b,NoGravity:1b,Marker:1b,CustomName:"torch"}
summon minecraft:armor_stand ~-2.0 ~-1.0 ~-6.0 {Invisible:1b,Invulnerable:1b,NoGravity:1b,Marker:1b,CustomName:"torch"}
summon minecraft:armor_stand ~-4.0 ~ ~5.0 {Invisible:1b,Invulnerable:1b,NoGravity:1b,Marker:1b,CustomName:"torch"}
summon minecraft:armor_stand ~-1.0 ~-6.0 ~1.0 {Invisible:1b,Invulnerable:1b,NoGravity:1b,Marker:1b,CustomName:"torch"}
summon minecraft:armor_stand ~-5.0 ~2.0 ~2.0 {Invisible:1b,Invulnerable:1b,NoGravity:1b,Marker:1b,CustomName:"torch"}
summon minecraft:armor_stand ~-3.0 ~4.5 ~-2.0 {Invisible:1b,Invulnerable:1b,NoGravity:1b,Marker:1b,CustomName:"torch"}
summon minecraft:armor_stand ~-3.0 ~-1.0 ~5.5 {Invisible:1b,Invulnerable:1b,NoGravity:1b,Marker:1b,CustomName:"torch"}
summon minecraft:armor_stand ~-1.0 ~-6.0 ~-1.0 {Invisible:1b,Invulnerable:1b,NoGravity:1b,Marker:1b,CustomName:"torch"}
summon minecraft:armor_stand ~2.0 ~3.0 ~5.0 {Invisible:1b,Invulnerable:1b,NoGravity:1b,Marker:1b,CustomName:"torch"}
summon minecraft:armor_stand ~3.0 ~-4.5 ~-2.0 {Invisible:1b,Invulnerable:1b,NoGravity:1b,Marker:1b,CustomName:"torch"}
summon minecraft:armor_stand ~4.0 ~-4.0 ~-2.0 {Invisible:1b,Invulnerable:1b,NoGravity:1b,Marker:1b,CustomName:"torch"}